//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ tùng.
        /// </summary>
        internal static string accessary {
            get {
                return ResourceManager.GetString("accessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phụ tùng.
        /// </summary>
        internal static string access_code {
            get {
                return ResourceManager.GetString("access_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phụ tùng.
        /// </summary>
        internal static string access_name {
            get {
                return ResourceManager.GetString("access_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đăng nhập.
        /// </summary>
        internal static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích hoạt.
        /// </summary>
        internal static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày kích hoạt.
        /// </summary>
        internal static string active_date {
            get {
                return ResourceManager.GetString("active_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào mừng thành viên của TEKA, để kích hoạt sản phẩm vui lòng điền đầy đủ thông tin dưới đây..
        /// </summary>
        internal static string active_description {
            get {
                return ResourceManager.GetString("active_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích hoạt.
        /// </summary>
        internal static string active_list {
            get {
                return ResourceManager.GetString("active_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bổ sung sau.
        /// </summary>
        internal static string add_late {
            get {
                return ResourceManager.GetString("add_late", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại lý.
        /// </summary>
        internal static string agent {
            get {
                return ResourceManager.GetString("agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THÔNG TIN ĐẠI LÝ.
        /// </summary>
        internal static string agent_info {
            get {
                return ResourceManager.GetString("agent_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên điểm bán hàng.
        /// </summary>
        internal static string agent_store {
            get {
                return ResourceManager.GetString("agent_store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã trả lời.
        /// </summary>
        internal static string answered {
            get {
                return ResourceManager.GetString("answered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết.
        /// </summary>
        internal static string article {
            get {
                return ResourceManager.GetString("article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        internal static string birthday {
            get {
                return ResourceManager.GetString("birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đem về trạm.
        /// </summary>
        internal static string bringback {
            get {
                return ResourceManager.GetString("bringback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bận.
        /// </summary>
        internal static string busy {
            get {
                return ResourceManager.GetString("busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày mua hàng.
        /// </summary>
        internal static string buydate {
            get {
                return ResourceManager.GetString("buydate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang gọi.
        /// </summary>
        internal static string calling {
            get {
                return ResourceManager.GetString("calling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng đài.
        /// </summary>
        internal static string call_center {
            get {
                return ResourceManager.GetString("call_center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày gọi.
        /// </summary>
        internal static string call_date {
            get {
                return ResourceManager.GetString("call_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đầu số gọi ra.
        /// </summary>
        internal static string call_key {
            get {
                return ResourceManager.GetString("call_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gọi ngay.
        /// </summary>
        internal static string call_now {
            get {
                return ResourceManager.GetString("call_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TG gọi.
        /// </summary>
        internal static string call_time {
            get {
                return ResourceManager.GetString("call_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gọi đến.
        /// </summary>
        internal static string call_to {
            get {
                return ResourceManager.GetString("call_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy bỏ.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân loại.
        /// </summary>
        internal static string cate {
            get {
                return ResourceManager.GetString("cate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại dịch vụ.
        /// </summary>
        internal static string cate_service {
            get {
                return ResourceManager.GetString("cate_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRUNG TÂM CHĂM SÓC KHÁCH HÀNG.
        /// </summary>
        internal static string center_warranti {
            get {
                return ResourceManager.GetString("center_warranti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kênh.
        /// </summary>
        internal static string chanel {
            get {
                return ResourceManager.GetString("chanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        internal static string change_pass {
            get {
                return ResourceManager.GetString("change_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Để thay đổi mật khẩu, vui lòng điền đầy đủ thông tin form dưới đây..
        /// </summary>
        internal static string change_pass_des {
            get {
                return ResourceManager.GetString("change_pass_des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyển trạm.
        /// </summary>
        internal static string change_station {
            get {
                return ResourceManager.GetString("change_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tính phí.
        /// </summary>
        internal static string charge {
            get {
                return ResourceManager.GetString("charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ định thợ.
        /// </summary>
        internal static string choose_ktv {
            get {
                return ResourceManager.GetString("choose_ktv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phiếu không đúng.
        /// </summary>
        internal static string code_notvalid {
            get {
                return ResourceManager.GetString("code_notvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phiếu BH.
        /// </summary>
        internal static string code_warranti {
            get {
                return ResourceManager.GetString("code_warranti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đồng ý thực hiện thao tác này?.
        /// </summary>
        internal static string comfirm {
            get {
                return ResourceManager.GetString("comfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIÊN HỆ.
        /// </summary>
        internal static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        internal static string content {
            get {
                return ResourceManager.GetString("content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        internal static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số yêu cầu nhận.
        /// </summary>
        internal static string count_warranti {
            get {
                return ResourceManager.GetString("count_warranti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tạo.
        /// </summary>
        internal static string createdate {
            get {
                return ResourceManager.GetString("createdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TẠO MỚI.
        /// </summary>
        internal static string create_new {
            get {
                return ResourceManager.GetString("create_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt lịch.
        /// </summary>
        internal static string create_warranti {
            get {
                return ResourceManager.GetString("create_warranti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        internal static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng kích hoạt.
        /// </summary>
        internal static string customer_active {
            get {
                return ResourceManager.GetString("customer_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string cus_address {
            get {
                return ResourceManager.GetString("cus_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quận/Huyện.
        /// </summary>
        internal static string cus_district {
            get {
                return ResourceManager.GetString("cus_district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        internal static string cus_name {
            get {
                return ResourceManager.GetString("cus_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        internal static string cus_phone {
            get {
                return ResourceManager.GetString("cus_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh/Thành phố.
        /// </summary>
        internal static string cus_province {
            get {
                return ResourceManager.GetString("cus_province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạn BH(Tháng).
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày dự kiến.
        /// </summary>
        internal static string deadline {
            get {
                return ResourceManager.GetString("deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả trang chủ.
        /// </summary>
        internal static string des_for_home {
            get {
                return ResourceManager.GetString("des_for_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian (ngày).
        /// </summary>
        internal static string duration {
            get {
                return ResourceManager.GetString("duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hạn bảo hành.
        /// </summary>
        internal static string end_date {
            get {
                return ResourceManager.GetString("end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi lắp đặt.
        /// </summary>
        internal static string err_install {
            get {
                return ResourceManager.GetString("err_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi sản phẩm.
        /// </summary>
        internal static string err_product {
            get {
                return ResourceManager.GetString("err_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi sử dụng.
        /// </summary>
        internal static string err_use {
            get {
                return ResourceManager.GetString("err_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất kho.
        /// </summary>
        internal static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày xuất kho.
        /// </summary>
        internal static string exportdate {
            get {
                return ResourceManager.GetString("exportdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất file.
        /// </summary>
        internal static string export_file {
            get {
                return ResourceManager.GetString("export_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi phí.
        /// </summary>
        internal static string fee {
            get {
                return ResourceManager.GetString("fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí phụ tùng.
        /// </summary>
        internal static string fee_access {
            get {
                return ResourceManager.GetString("fee_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí di chuyển.
        /// </summary>
        internal static string fee_move {
            get {
                return ResourceManager.GetString("fee_move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phí bảo hành.
        /// </summary>
        internal static string fee_warranti {
            get {
                return ResourceManager.GetString("fee_warranti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo trạm.
        /// </summary>
        internal static string for_station {
            get {
                return ResourceManager.GetString("for_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ số.
        /// </summary>
        internal static string from_number {
            get {
                return ResourceManager.GetString("from_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HƯỚNG DẪN KÍCH HOẠT.
        /// </summary>
        internal static string help_active {
            get {
                return ResourceManager.GetString("help_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử gọi.
        /// </summary>
        internal static string history_call {
            get {
                return ResourceManager.GetString("history_call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ tổng đài.
        /// </summary>
        internal static string home_hotline {
            get {
                return ResourceManager.GetString("home_hotline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu ý khách hàng có thể kích hoạt và báo lỗi sản phẩm qua tổng đài.
        /// </summary>
        internal static string home_note {
            get {
                return ResourceManager.GetString("home_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        internal static string index {
            get {
                return ResourceManager.GetString("index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THÔNG TIN HỖ TRỢ.
        /// </summary>
        internal static string info_help {
            get {
                return ResourceManager.GetString("info_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THÔNG TIN SẢN PHẨM.
        /// </summary>
        internal static string info_prod {
            get {
                return ResourceManager.GetString("info_prod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin lịch.
        /// </summary>
        internal static string info_warranti {
            get {
                return ResourceManager.GetString("info_warranti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập serial sản phẩm.
        /// </summary>
        internal static string input_serial {
            get {
                return ResourceManager.GetString("input_serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lắp đặt.
        /// </summary>
        internal static string install {
            get {
                return ResourceManager.GetString("install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày lắp đặt.
        /// </summary>
        internal static string installdate {
            get {
                return ResourceManager.GetString("installdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng đăng nhập theo form dưới đây.
        /// </summary>
        internal static string login_des {
            get {
                return ResourceManager.GetString("login_des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KÍCH HOẠT BẢO HÀNH TRỰC TUYẾN.
        /// </summary>
        internal static string menu_active {
            get {
                return ResourceManager.GetString("menu_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HƯỚNG DẪN.
        /// </summary>
        internal static string menu_help {
            get {
                return ResourceManager.GetString("menu_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANG CHỦ.
        /// </summary>
        internal static string menu_home {
            get {
                return ResourceManager.GetString("menu_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐĂNG NHẬP.
        /// </summary>
        internal static string menu_login {
            get {
                return ResourceManager.GetString("menu_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRA CỨU.
        /// </summary>
        internal static string menu_search {
            get {
                return ResourceManager.GetString("menu_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐẶT LỊCH TRỰC TUYẾN.
        /// </summary>
        internal static string menu_warranti {
            get {
                return ResourceManager.GetString("menu_warranti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mới tạo.
        /// </summary>
        internal static string news {
            get {
                return ResourceManager.GetString("news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa kích hoạt.
        /// </summary>
        internal static string not_active {
            get {
                return ResourceManager.GetString("not_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không trả lời.
        /// </summary>
        internal static string not_answer {
            get {
                return ResourceManager.GetString("not_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quá hạn.
        /// </summary>
        internal static string outdate {
            get {
                return ResourceManager.GetString("outdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận mật khẩu.
        /// </summary>
        internal static string pass_confirm {
            get {
                return ResourceManager.GetString("pass_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        internal static string pass_new {
            get {
                return ResourceManager.GetString("pass_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu hiện tại.
        /// </summary>
        internal static string pass_now {
            get {
                return ResourceManager.GetString("pass_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanh toán.
        /// </summary>
        internal static string payment {
            get {
                return ResourceManager.GetString("payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa thanh toán.
        /// </summary>
        internal static string payment_not {
            get {
                return ResourceManager.GetString("payment_not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thanh toán.
        /// </summary>
        internal static string payment_ok {
            get {
                return ResourceManager.GetString("payment_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận thanh toán.
        /// </summary>
        internal static string pay_check {
            get {
                return ResourceManager.GetString("pay_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TG tính tiền.
        /// </summary>
        internal static string pay_time {
            get {
                return ResourceManager.GetString("pay_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại/ Serial này không tồn tại trong hệ thống TEKA..
        /// </summary>
        internal static string phoneserial_not_valid {
            get {
                return ResourceManager.GetString("phoneserial_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại kích hoạt.
        /// </summary>
        internal static string phone_active {
            get {
                return ResourceManager.GetString("phone_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số liên hệ.
        /// </summary>
        internal static string phone_call {
            get {
                return ResourceManager.GetString("phone_call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        internal static string photo {
            get {
                return ResourceManager.GetString("photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng điền đầy đủ họ tên để TEKA hỗ trợ tốt nhất.
        /// </summary>
        internal static string place_teka_good {
            get {
                return ResourceManager.GetString("place_teka_good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phát file ghi âm.
        /// </summary>
        internal static string play_rec {
            get {
                return ResourceManager.GetString("play_rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHÍNH SÁCH BẢO HÀNH.
        /// </summary>
        internal static string policy {
            get {
                return ResourceManager.GetString("policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xử lý.
        /// </summary>
        internal static string processing {
            get {
                return ResourceManager.GetString("processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm.
        /// </summary>
        internal static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả sản phẩm.
        /// </summary>
        internal static string product_cate_list {
            get {
                return ResourceManager.GetString("product_cate_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm xuất kho.
        /// </summary>
        internal static string product_list {
            get {
                return ResourceManager.GetString("product_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại sản phẩm.
        /// </summary>
        internal static string prod_cate {
            get {
                return ResourceManager.GetString("prod_cate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sản phẩm.
        /// </summary>
        internal static string prod_code {
            get {
                return ResourceManager.GetString("prod_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm.
        /// </summary>
        internal static string prod_name {
            get {
                return ResourceManager.GetString("prod_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thông tin sản phẩm.
        /// </summary>
        internal static string prod_notvalid {
            get {
                return ResourceManager.GetString("prod_notvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial sản phẩm.
        /// </summary>
        internal static string prod_serial {
            get {
                return ResourceManager.GetString("prod_serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PXK.
        /// </summary>
        internal static string PXK {
            get {
                return ResourceManager.GetString("PXK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câu hỏi.
        /// </summary>
        internal static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoản cách.
        /// </summary>
        internal static string range {
            get {
                return ResourceManager.GetString("range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi âm.
        /// </summary>
        internal static string rec {
            get {
                return ResourceManager.GetString("rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu hồi.
        /// </summary>
        internal static string recall {
            get {
                return ResourceManager.GetString("recall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm từ chối.
        /// </summary>
        internal static string refuse_station {
            get {
                return ResourceManager.GetString("refuse_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê bảo hành.
        /// </summary>
        internal static string report_warranti {
            get {
                return ResourceManager.GetString("report_warranti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các đề mục đánh dấu sao (*) là bắt buộc.
        /// </summary>
        internal static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả.
        /// </summary>
        internal static string result {
            get {
                return ResourceManager.GetString("result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐIỀU KHOẢN KÍCH HOẠT.
        /// </summary>
        internal static string rule_active {
            get {
                return ResourceManager.GetString("rule_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu thông tin.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRA CỨU THÔNG TIN KÍCH HOẠT BẢO HÀNH.
        /// </summary>
        internal static string sch_active {
            get {
                return ResourceManager.GetString("sch_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào mừng thành viên của TEKA, để tra cứu bảo hành vui lòng điền đầy đủ thông tin dưới đây..
        /// </summary>
        internal static string sch_active_des {
            get {
                return ResourceManager.GetString("sch_active_des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRA CỨU THÔNG TIN BẢO HÀNH.
        /// </summary>
        internal static string sch_warranti {
            get {
                return ResourceManager.GetString("sch_warranti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào mừng thành viên của TEKA, để tra cứu bảo hành vui lòng điền đầy đủ thông tin dưới đây..
        /// </summary>
        internal static string sch_warranti_des {
            get {
                return ResourceManager.GetString("sch_warranti_des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRA CỨU KÍCH HOẠT.
        /// </summary>
        internal static string search_active {
            get {
                return ResourceManager.GetString("search_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRA CỨU KÍCH HOẠT SẢN PHẨM.
        /// </summary>
        internal static string search_active_product {
            get {
                return ResourceManager.GetString("search_active_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi notifi.
        /// </summary>
        internal static string sent_notifi {
            get {
                return ResourceManager.GetString("sent_notifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRUNG TÂM BẢO HÀNH ĐIỆN TỬ TEKA.
        /// </summary>
        internal static string slogan {
            get {
                return ResourceManager.GetString("slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại lý kích hoạt.
        /// </summary>
        internal static string sms_active {
            get {
                return ResourceManager.GetString("sms_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sắp xếp.
        /// </summary>
        internal static string sort {
            get {
                return ResourceManager.GetString("sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        internal static string start_date {
            get {
                return ResourceManager.GetString("start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm bảo hành.
        /// </summary>
        internal static string station {
            get {
                return ResourceManager.GetString("station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hết hạn.
        /// </summary>
        internal static string status_end {
            get {
                return ResourceManager.GetString("status_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa kích hoạt.
        /// </summary>
        internal static string status_not {
            get {
                return ResourceManager.GetString("status_not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã kích hoạt.
        /// </summary>
        internal static string status_ok {
            get {
                return ResourceManager.GetString("status_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cửa hàng.
        /// </summary>
        internal static string store {
            get {
                return ResourceManager.GetString("store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hoàn thành.
        /// </summary>
        internal static string succ_date {
            get {
                return ResourceManager.GetString("succ_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền.
        /// </summary>
        internal static string sum_money {
            get {
                return ResourceManager.GetString("sum_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế.
        /// </summary>
        internal static string taxcode {
            get {
                return ResourceManager.GetString("taxcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kỹ thuật viên.
        /// </summary>
        internal static string technicians {
            get {
                return ResourceManager.GetString("technicians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến số.
        /// </summary>
        internal static string to_number {
            get {
                return ResourceManager.GetString("to_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật trạng thái.
        /// </summary>
        internal static string update_status {
            get {
                return ResourceManager.GetString("update_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chờ linh kiện.
        /// </summary>
        internal static string wait_access {
            get {
                return ResourceManager.GetString("wait_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chờ phản hồi.
        /// </summary>
        internal static string wait_response {
            get {
                return ResourceManager.GetString("wait_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảo hành.
        /// </summary>
        internal static string warranti {
            get {
                return ResourceManager.GetString("warranti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận bảo hành.
        /// </summary>
        internal static string warranti_check {
            get {
                return ResourceManager.GetString("warranti_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhiều sản phẩm.
        /// </summary>
        internal static string warranti_multi_prod {
            get {
                return ResourceManager.GetString("warranti_multi_prod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn thành phiếu.
        /// </summary>
        internal static string warranti_success {
            get {
                return ResourceManager.GetString("warranti_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới thông tin bảo hành.
        /// </summary>
        internal static string war_create {
            get {
                return ResourceManager.GetString("war_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả lỗi.
        /// </summary>
        internal static string war_des {
            get {
                return ResourceManager.GetString("war_des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        internal static string war_note {
            get {
                return ResourceManager.GetString("war_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người phụ trách.
        /// </summary>
        internal static string war_person {
            get {
                return ResourceManager.GetString("war_person", resourceCulture);
            }
        }
    }
}
