//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEKA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddKey
    {
        public long Id { get; set; }
        public Nullable<long> IdWarranti { get; set; }
        public string IdKey { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<System.DateTime> Successdate { get; set; }
        public string Note { get; set; }
        public Nullable<int> Cost { get; set; }
        public string Comeback { get; set; }
        public string Device { get; set; }
        public string IdKTV { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
        public string Image5 { get; set; }
        public string Image6 { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Long { get; set; }
        public string KM { get; set; }
        public Nullable<int> MoveFee { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Sign { get; set; }
        public string CateError { get; set; }
        public Nullable<int> Service_price { get; set; }
        public string Name_price { get; set; }
        public string Distance { get; set; }
        public Nullable<int> DistanceFee { get; set; }
        public Nullable<int> TravelFee { get; set; }
        public Nullable<int> AccessaryFee { get; set; }
        public Nullable<int> CharFee { get; set; }
        public Nullable<int> PubFee { get; set; }
    }
}
