//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEKA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<int> Status { get; set; }
        public string CodeProduct { get; set; }
        public string Serial { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public string NameAgency { get; set; }
        public string CodeAgency { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ErrorNote { get; set; }
        public Nullable<int> Type { get; set; }
        public string Message { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public Nullable<int> ActiveWho { get; set; }
        public Nullable<System.DateTime> ErrorDate { get; set; }
        public Nullable<int> StatusError { get; set; }
        public Nullable<System.DateTime> Buydate { get; set; }
        public Nullable<System.DateTime> Installdate { get; set; }
        public string Ward { get; set; }
    }
}
