//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEKA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public long Id { get; set; }
        public string Model1 { get; set; }
        public string Code { get; set; }
        public string ProductCate { get; set; }
        public string GroupCode { get; set; }
        public string OLDCate { get; set; }
    }
}
