//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEKA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phutung_Warranti
    {
        public long Id { get; set; }
        public Nullable<long> IdKey { get; set; }
        public Nullable<long> IdDevice { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Amount { get; set; }
    }
}
