//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEKA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Serial { get; set; }
        public string Model { get; set; }
        public string PXK { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public Nullable<int> Limited { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string PhoneActive { get; set; }
        public string PhoneSend { get; set; }
        public string NameAgency { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public string ThanhToan { get; set; }
        public string UserName { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> Buydate { get; set; }
        public Nullable<System.DateTime> Installdate { get; set; }
    }
}
