//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEKA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service_Fee
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public Nullable<int> Warfee { get; set; }
        public Nullable<int> Charfee { get; set; }
        public Nullable<int> Pubfee { get; set; }
    }
}
