//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEKA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TEKAEntities : DbContext
    {
        public TEKAEntities()
            : base("name=TEKAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Ward> Wards { get; set; }
        public virtual DbSet<QuayThuong> QuayThuongs { get; set; }
        public virtual DbSet<LogWaranti> LogWarantis { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<DeviceSendKey> DeviceSendKeys { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ImageWarr> ImageWarrs { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<User_Device> User_Device { get; set; }
        public virtual DbSet<Phutung_Warranti> Phutung_Warranti { get; set; }
        public virtual DbSet<MoveFee> MoveFees { get; set; }
        public virtual DbSet<Setup> Setups { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<AddKey> AddKeys { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<Warranti> Warrantis { get; set; }
        public virtual DbSet<SentNotifi> SentNotifis { get; set; }
        public virtual DbSet<CurrentURL> CurrentURLs { get; set; }
        public virtual DbSet<LOG_MO> LOG_MO { get; set; }
        public virtual DbSet<Service_Fee> Service_Fee { get; set; }
    }
}
