//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEKA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warranti
    {
        public long Id { get; set; }
        public string CodeWarr { get; set; }
        public Nullable<long> IdCustomer { get; set; }
        public string Phone { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Ward { get; set; }
        public string District { get; set; }
        public string Province { get; set; }
        public string PhoneWarr { get; set; }
        public Nullable<long> IdProduct { get; set; }
        public string ProductCate { get; set; }
        public string Product { get; set; }
        public string Serial { get; set; }
        public string Model { get; set; }
        public string Agent { get; set; }
        public Nullable<System.DateTime> Buydate { get; set; }
        public Nullable<System.DateTime> Activedate { get; set; }
        public Nullable<int> Limited { get; set; }
        public string Note { get; set; }
        public Nullable<int> Status { get; set; }
        public string Chanel { get; set; }
        public string Category { get; set; }
        public string Createby { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string Extra { get; set; }
        public string CateError { get; set; }
        public bool Outdate { get; set; }
        public Nullable<int> CountDay { get; set; }
        public Nullable<bool> Checked { get; set; }
    }
}
